### ISSUE TITLE
sync with zotero

### ISSUE THREAD

**Issue by colcord** [openannotation/annotator#124]
I have been using zotero to bookmark and annotate web pages since 2008.
Before that I used Furl.
I would look at annotator, if I knew I could sync any thing I did with annotator with my existing work in zotero.
Zotero has a lot of plug ins.

**Comment by samspo** [comment]
Hi Nick,
Just seen this old conversation.
Would be wonderfull if there was a firefox plugin that allow the use of annotateit on the html documents of the zotero database (a plugin that would be closely related to zotero, just like http://zotfile.com/)
The more useful for me would be to have a local storage of annotations.

**Comment by tilgovi** [comment]
@samspo I'm not sure I understand what you mean by "use of annotateit on the html documents of the zotero database". Can you clarify?

**Comment by tilgovi** [comment]
It sounds like you're saying to annotate the documents that zotero stores references to, but I think you want to say store annotations in the zotero database.

**Comment by samspo** [comment]
To be honnest, I don't know if it could be in the zotero database (but it would be very cool if possible). I would like to be able to annotate the html files (and maybe other files if possible, I see that there is a video annotator and an image annotator) in order to store somewhere on my computer my annotations (in order to see my previous annotations when I open the html file).

It could be a zotero plugin (like this one : https://addons.mozilla.org/fr/firefox/addon/annotate-it/?src=api), but applied to offline files and without need to have an account on http://annotateit.org/. Would be very useful to also have the:
- tags-annotator https://github.com/lduarte1991/tags-annotator
- Margin Viewer Plugin: https://github.com/habeanf/annotator/blob/master/src/plugin/marginviewer.coffee

It would be something like hypothes.is but offline and linked to zotero.

Juste few ideas, but I can try to elaborate more if useful. I'm juste a user. I see exactly the usecases but don't have any ideas about the technical implications of that.

**Comment by tilgovi** [comment]
Clearly a useful idea, but I'm afraid I'd say it's a bit out of scope for this repository. While we do build a bookmarklet, the landscape of JavaScript development has evolved in the last few years dramatically.

Anyone interested in implementing this should start a repository, include the annotator, and bring it up on the mailing list for interested collaborators to get involved.

**Comment by samspo** [comment]
Thank you for your answer.
