### ISSUE TITLE
I can't find an option to disable the annotator plugin

### ISSUE THREAD

**Issue by DT-Tijme** [openannotation/annotator#551]
There does not seem to be an option to disable the annotator plugin (toggle with button). Can this be created? 

    Something like $(element).annotator(false);

**Comment by tilgovi** [comment]
`$(element).annotator('destroy');` work?

**Comment by DT-Tijme** [comment]
@tilgovi It does, thanks!

**Comment by tilgovi** [comment]
You're correct. So sorry about that!

The method is documented for the upcoming 2.0 release:
http://annotator.readthedocs.org/en/latest/api/app.html#annotator.App.prototype.destroy

Since that is the focus of development right now I think I'll just close this, but feel free to send a PR for the v1.2.x branch if you feel compelled.

Thanks!
