### ISSUE TITLE
Suggest move some Range-related features from ui.main to core 

### ISSUE THREAD

**Issue by CNDLS** [openannotation/annotator#567]
annotationFactory & the related Range objects would be useful to developers who might need to provide their own ui. Consider placing these in core code, so ui.main or ui.textselector would not have to be loaded to use them.

**Comment by tilgovi** [comment]
Have you seen openannotation/xpath-range?

**Comment by tilgovi** [comment]
Weird, I thought GitHub would linkify that. Here it is. https://github.com/openannotation/xpath-range

**Comment by tilgovi** [comment]
Also, just so I'm clear, is the request you're making that these modules be exported in the `annotator` namespace so they can be used from the standalone bundle and considered public library surface area for those who are consuming the final bundle and can't, for instance, `require('annotator/ui/textselector')`?

**Comment by CNDLS** [comment]
Thanks. I had seen xpath-range a while ago but had forgotten about it. Yes, that's right; I was suggesting exporting these modules in the annotator namespace, or perhaps, if you're looking toward integrating the video annotation tool & eventually annotating other media, you could have media-specific namespaces/modules, eg; (text | image | video ...).selection, (text | image | video ...).highlight, etc.

**Comment by tilgovi** [comment]
I think I'm going to close this.

`xpath-range` exposes the core parts of what `annotator` uses for anchoring to text today.
In the future, I don't think we should export more support in the `annotator` namespace because I would like this to be left to 3rd party modules. That, I hope, encourages more community participation, more experimentation, and more decentralized maintenance. It also increases the transparency around who is familiar with what, because the participants in any given module's maintenance are clear rather than having a whole lot of contributors to a single monolithic package, hopefully making it easier to get answers and help. It also means it's easier to release because you can make changes to one module while other packages remain pinned to older versions without having to update the world. For instance, as it stands right now, I'm sort of wringing my hands about what to do about packaging the `document` and `unsupported` and that's sort of holding up 2.0. I may just delete them for the time being, release without them, and re-instate them as 3rd party.

I'm going to work on getting the packaging finalized and 2.0 released and then we can start growing the ecosystem.
