### ISSUE TITLE
annotateit.org TLS certificate broken (=> API calls not possible from HTTPS site)

### ISSUE THREAD

**Issue by melat0nin** [openannotation/annotator#612]
Hi all

I'm trying to set up annotator on my site which uses TLS, but I can't interface with the API because the annotateit.org certificate is invalid so connection is nixed by the browser.

Is there any chance the certificate can be fixed to enable use by TLS sites?

**Comment by tilgovi** [comment]
This is because AnnotateIt is hosted on Heroku and never had TLS set up. You're seeing the default heroku cert that is for the *.herokuapp.com domain.

Unfortunately, this has nothing to do with annotator itself. There's an issue for this that's been open for a long time on openannotation/annotateit#10.

The truth is that no one has been maintaining AnnotateIt for some time. I've opened an issue to discuss that at openannotation/annotateit#22. I apologize because it's long overdue.

At this point, I'm going to close this issue and invite you to move the discussion to those places. Thanks.
