### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by victoryhb** [openannotation/annotator#623]
Hi! We're trying to decide whether to use this excellent Annotator library in one of our new projects for text-based annotation. However, it has been almost a year since a new release was made, which doesn't seem normal for a high-profile project like this. Has this project been abandoned?

Best,
Victor

**Comment by tilgovi** [comment]
It has not been abandoned, though there has been some community introspection about the scope of efforts we can support.

Please see recent traffic on the mailing list, especially the thread "Recap Call Sunday June 19, 2016": http://thread.gmane.org/gmane.comp.web.annotator/

**Comment by bgarr** [comment]
Hey,
Thanks for the letting us know about the change in direction and for the
project, generally. It's been great to work with.

I'm not clear if the spreadsheet should be added to by just anybody, so
I'll just post our project as an implementation idea. We set out to make a
more event-driven mechanism, because our intended workflow(s) seemed to
differ too much from the original. It's not a library for your reference
sheet, but there may be something to having library pieces emit and receive
events. Just a suggestion:  https://github.com/CNDLS/annotator

Cheers,
Bill Garr

**Comment by tilgovi** [comment]
Bill, I agree with you. However, the Annotator events didn't seem quite right to me and were being used for things where results and completion notifications were desired. I'm hesitant to add events again, and instead I'm going to focus on removing the framework aspects.

Once the components are cleanly packaged, we might all tackle an events interface together. @aron, @nickstenning and I had a design session a bit over a year ago and that resulted in https://github.com/nickstenning/domannotations but development stalled.

**Comment by tilgovi** [comment]
@bgarr it looks like your annotator does something like what I have in mind for #585. I think it would be great to collaborate on something, external to Annotator, that makes this a first class re-usable library. For inspiration, I would look to Atom (http://blog.atom.io/2015/06/16/optimizing-an-important-atom-primitive.html). I haven't actually dug far enough to discover whether their code is extractable in its current form. Possibly a standalone rewrite of that would be a useful primitive for all manner of text application.

**Comment by tilgovi** [comment]
Ah, I was mis-remembering a bit. You have a _block_ manager, not a _mark_ manager.
